-- 코드를 입력하세요
SELECT c.car_ID, c.car_type, ROUND(c.DAILY_FEE - (c.DAILY_FEE/100 * d.DISCOUNT_RATE))*30 FEE FROM CAR_RENTAL_COMPANY_CAR c JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON c.CAR_TYPE = d.CAR_TYPE
WHERE c.CAR_TYPE IN('세단', 'SUV') 
AND d.DURATION_TYPE = '30일 이상' 
GROUP BY c.CAR_ID    
HAVING MAX(h.end_date)<="2022-11-01"
AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY 3 DESC, 2 ASC, 1 DESC;