-- 코드를 입력하세요
SELECT DISTINCT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT p JOIN FOOD_ORDER o
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = '2022' 
AND MONTH(o.PRODUCE_DATE) = '05'
GROUP BY p.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC