WITH RECURSIVE cte AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1
    FROM CTE
    WHERE NUM < 23
)

SELECT C.NUM, IFNULL(A.COUNT, 0)
FROM CTE C
LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
           FROM ANIMAL_OUTS
           GROUP BY HOUR
           ORDER BY HOUR) A
ON C.NUM = A.HOUR;