SELECT 
    CASE
        WHEN name = 'Python' AND CATEGORY = 'Front End' THEN 'A'
        WHEN name = 'C#' THEN 'B'
        WHEN CATEGORY = 'Front End' THEN 'C'
    END AS GRADE, 
    DEVELOPERS.ID, 
    DEVELOPERS.EMAIL 
FROM SKILLCODES
JOIN DEVELOPERS 
    ON SKILLCODES.CODE = DEVELOPERS.SKILL_CODE
WHERE EXIST GRADE
GROUP BY GRADE, DEVELOPERS.ID, DEVELOPERS.EMAIL  -- Corrected GROUP BY
ORDER BY GRADE, DEVELOPERS.ID;
